FROM python:3.14-slim

COPY --from=ghcr.io/astral-sh/uv:0.12.5 /uv /uvx /bin/

ENV PATH="/opt/venv/bin:${PATH}" \
    PYTHONPATH="/workspace" \
    UV_LINK_MODE=copy \
    UV_PROJECT_ENVIRONMENT=/opt/venv

WORKDIR /opt/project

COPY pyproject.toml README.md uv.lock ./

RUN uv sync --frozen --no-install-project

WORKDIR /workspace

ENTRYPOINT ["pytest"]
